workingdir: ''
sra: ERR6608653 # SRA number of the reads to download
genome: GCA_910589525.2 # GCA number of the reference genome to download
name: e_quercinarius # name of the species to study
min_coverage: 10 # minimum of coverage for the SV callers
min_sv_size: 50 # minimum SV length to detect
