# CONFIG
# Directory setup
datadir: data/ # The directory where data and results must be stored

# SAMPLE
samples: config/samples.tsv # The sample files with sample name and SRA number of the long-read SRA archive
genome: GCA_947369205.1 # GCA/GCF number of the reference genome

# Mapping on the reference genome
minimap_ax: map-hifi # Preset for the sequencing technology (see Minimap2 manual)
minimap_seed: 42 # Integer seed for randomizing equally best hits. Minimap2 hashes INT and read name when choosing between equally best hits.

# SV calling
# Common settings
min_coverage: 10 # minimum of coverage for the SV callers
min_sv_size: 50 # minimum SV length to detect

# Sniffles2 specific
minsupport: "auto" #  Minimum number of supporting reads for a SV to be reported (default: automatically choose based on coverage)
minsvlen-screen-ratio: 0.9 # minsvlen-screen-ratio N Minimum length for SV candidates (as fraction of --minsvlen) (default: 0.9)
mapq: 25 # mapq N Alignments with mapping quality lower than this value will be ignored (default: 25)

# SVIM specific
svim_quality: 10 # Minimum SV quality score in SVIM for filtering out the callset
segment_gap_tolerance: 10 #  Maximum tolerated gap between adjacent alignment segments (default: 10)
segment_overlap_tolerance: 5 # Maximum tolerated overlap between adjacent alignment (default: 5)

# CuteSV specific
max_cluster_bias_INS: 1000
diff_ratio_merging_INS: 0.9
max_cluster_bias_DEL: 1000
diff_ratio_merging_DEL: 0.5
max_size: -1


# DeBreak specific


# Merging with Jasmine/IRIS


# Genotyping with SVJedi-graph
minsupport: 3 # Minimum number of alignments to genotype a SV (default: 3>=)