# Mosdepth
quantize_cov_threshold_lower: 10 # Must be integer
quantize_cov_threshold_upper: 3 # Must be integer

# Genmap
## callable sites bed file options ##
mappability_min: 1 #regions of the genome with mappability less than this will be removed from callable sites bed file
mappability_k: 150 #the kmer used to compute mappability with genmap; you should not need to change this except in special cases

#this ignores small regions of abberatant coverage/mappability as often these are just below the threshold
#to do strict filtering, set to 0

mappability_merge: 100 #merge passing mappability regions separated by this or fewer bp into a single region
